// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Thu Aug 27 09:59:20 2020

sobel sobel_inst
(
	.rst(rst_sig) ,	// input  rst_sig
	.pclk(pclk_sig) ,	// input  pclk_sig
	.threshold(threshold_sig) ,	// input [7:0] threshold_sig
	.ycbcr_hs(ycbcr_hs_sig) ,	// input  ycbcr_hs_sig
	.ycbcr_vs(ycbcr_vs_sig) ,	// input  ycbcr_vs_sig
	.ycbcr_de(ycbcr_de_sig) ,	// input  ycbcr_de_sig
	.data_in(data_in_sig) ,	// input [7:0] data_in_sig
	.data_out(data_out_sig) ,	// output [7:0] data_out_sig
	.sobel_hs(sobel_hs_sig) ,	// output  sobel_hs_sig
	.sobel_vs(sobel_vs_sig) ,	// output  sobel_vs_sig
	.sobel_de(sobel_de_sig) 	// output  sobel_de_sig
);

